### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by Brand-Frank** [Brand-Frank/C51#5]
Here is something i want to to:
- [ ] ⭐ Finsh the first stage's learning.(完成第一阶段的学习。 - `7/14days`)
- [ ] Fix the `bug`.(修复在学习过程中写出的BUG。 - `0/3days`)
- [ ] Re-watch the video with the `manual`, and **_optimize code_**.(配合手册重新观看视频并优化代码：看不懂的地方可以结合普中的开发板视频、PPT来理解。 - `0/4days`)
- [ ] Make a `PCB` by myself.(自己绘制一块PCB板子，如果没思路，可以淘宝上买板子，看配套的板子电路原理图。 - `0/7days`)
- [ ] Use my own `development board` to do `DIY`.(使用自己的开发板去做DIY。)
